### ISSUE TITLE
Create test file if not exists

### ISSUE THREAD

**Issue by lonix1** [johnathanludwig/vscode-fileswitcher#14]
How hard would it be to add functionality for "create matching test file if not exists"? My thoughts were: 1) must be bound to a different shortcut, 2) must only work one-way, from source file to test file.

I've no experience writing vscode extensions, but nonetheless tried fiddling with the code but didn't succeed. I thought that once I get the mapping from the extension's current behavior, I can use node's `fs` functions to create the matching test file. I guess there's more to it than that?

I'm wondering whether there's enough in the extension so far to make this possible, or I need to add a whole raft of new stuff?

**Comment by johnathanludwig** [comment]
It looks like it should be possible through the [VS Code workspace API](https://code.visualstudio.com/api/references/vscode-api#WorkspaceEdit). Since there are multiple mappings you would need to select from the generated mappings which file you want to create. 

I'm not sure what the workflow should be. Should it pop up automatically when trying to switch files and there aren't any matches? It could be part of the current generated mappings quick pick, or a new command altogether.

Maybe both are ok. If you don't want to create the file you can just press escape.

**Comment by lonix1** [comment]
I was thinking about a new command, as that's less surprising to the user. But your way makes sense too - if it doesn't exist, ask the user whether he wants to automatically create it. I'm not sure... Need to think about it.

Ideally it could be a configurable setting, but that just makes it more complicated.

Thanks - you've given me a lot to get started with this!

**Comment by lonix1** [comment]
I took another stab at this, but just can't figure out these vscode extensions! :angry: :smile:

I'm gonna close, sorry for wasting your time!

(PS extension is still great, love using it!!!)

**Comment by johnathanludwig** [comment]
We can reopen. I've done some research and have gotten part way there on a branch. I'm sure it's possible — it's just a matter of finding the right VSCode APIs and time.

**Comment by lonix1** [comment]
I just installed the new version but couldn't figure out how to use it? When I press the key combo to go to the corresponding test file it shows the "can't find" message as before. What have I done wrong?

**Comment by johnathanludwig** [comment]
I went the new command route with no default keybinding. So instead of switching, open the command palette and run "Create file from mapping." Also it will only show mappings that match the current file where the target file is missing. I should probably make it display a message if there isn't any matches.

Also make sure vscode updated the extension, it is in 0.9.0.

**Comment by lonix1** [comment]
I didn't realise it was going to be a separate command - I tried that and it works really well... Thanks!

This new feature is incredibly useful, makes the extension "complete".

(BTW why did you opt to design the feature as a separate command?)

**Comment by johnathanludwig** [comment]
Well you made the initial argument for it 😉.

Ultimately though I think it might degrade the original command. Currently when trying to switch it will switch immediately if there is only one match. If there are multiple it shows you those matches. If I were to make that same command handle creating I would then have to show you all of the mappings every time, so you can see the missing files and create them.

**Comment by lonix1** [comment]
LOL well that was embarrasing... :laughing: 

Yep your logic makes perfect sense. I've been using it for a few hours and it makes everything so much easier! Thanks for implementing it.
